### ISSUE TITLE
Using gradient based attribution methods with TimesNet. 

### ISSUE THREAD

**Issue by idilkapikiran** [UVA-MLSys/SA-Timeseries#5]
Hello, I've been working on using Captum explainability methods with the TimesNet model for long-term forecasting and discovered this repository. Your work is similar to what I've been trying to achieve. Thus, I've looked into the notes in your repository about several mismatched attribution types with some of the models and possible problems. However, I haven't seen the issue I've encountered among them, so I wanted to ask if, at any point, this issue has been raised on your part as well.

After training, saving, and loading the TimesNet model for the long-term forecasting task, I calculate gradient-based attribution scores using DeepLift. I encountered an issue: "RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation." Using the anomaly detection "set_detect_anomaly," my issue was concerning the line 109 of the TimesNet.py, which is `x_enc /= stdev`. 
Have you encountered this problem before? If so, can you suggest a possible solution without modifying the model itself?
Thank you.

**Comment by khairulislam** [comment]
Hi @idilkapikiran, Thanks for your comment. I have used TimesNet here but only for classification and regression. About DeepLift, I found some compatibility issue with the tint library itself.  But haven't dived deeper into the problem for now.
